minimumReleaseAge: 1440 # minutes = 1 day

shellEmulator: true
autoInstallPeers: false # Why pnpm? Why?

trustPolicy: no-downgrade

allowBuilds:
  esbuild: true

packages:
  - 'packages/*'
  - docs
minimumReleaseAgeExclude:
  # Renovate security update: vitest@4.1.11
  - vitest@4.1.11
