catalogs:
  vue2:
    '@vue/composition-api': ^1.7.0
    '@vue/test-utils': ^1.3.5
    vue: npm:vue@^2.7.16
    vue-template-compiler: ^2.7.16
  vue3:
    '@vue/compiler-sfc': ^3.5.16
    '@vue/test-utils': ^2.4.6
    vue: npm:vue@^3.5.16
    vue-2: npm:vue@^2.7.16
    vue-3: npm:vue@^3.5.16
