name: Ship js trigger
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v2.4.1
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: '14'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x
          run_install: true

      - run: npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
