name: Size
on:
  pull_request:
    branches:
      - main
    paths:
      - packages/fluent-vue/**
      - pnpm-lock.yaml
      - .github/workflows/size.yml
env:
  CI: true

permissions:
  contents: read
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
      COREPACK_ENABLE_STRICT: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Setup
        uses: ./.github/actions/setup

      - name: Check size changes
        uses: antfu/export-size-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: packages/fluent-vue
          build_script: pnpm -C packages/fluent-vue build
