name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CI: true

permissions:
  contents: read

jobs:
  test-fluent-vue:
    name: 'fluent-vue: Node.js ${{ matrix.node }} / OS: ${{ matrix.os }} / Vue: ${{ matrix.vue }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [22, 24]
        vue: [2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        run: pnpm -C packages/fluent-vue test:${{ matrix.vue }} --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v7
        with:
          flags: fluent-vue-vue${{ matrix.vue }}
          token: ${{ secrets.CODECOV_TOKEN }}

  test-unplugin:
    name: 'unplugin-fluent-vue: Node.js ${{ matrix.node }} / OS: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [22, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        run: pnpm -C packages/unplugin-fluent-vue test:coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v7
        with:
          flags: unplugin-fluent-vue
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    name: Lint source code
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint
      - name: Type check
        run: pnpm typecheck

  publish:
    runs-on: ubuntu-latest
    name: Publish test build to pkg.pr.new
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpx pkg-pr-new publish './packages/*'

  test-examples:
    runs-on: ubuntu-latest
    name: Test build of example projects
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup
        uses: ./.github/actions/setup

      - name: Checkout examples
        uses: actions/checkout@v6.0.2
        with:
          repository: fluent-vue/examples
          path: examples

      - name: Test
        run: node packages/fluent-vue/scripts/build-examples.mjs
